#!/usr/bin/env bash
# Bash script that will display information about subdomains.
function domain_check {
	domain_names=("www" "lb-01" "web-01" "web-02")

	for i in "${domain_names[@]}";
	do
		dig "${i}"."$1" +noall +answer | \
            awk -v subdomain="$i" '{print "The subdomain", subdomain, "is a", $4, "record and points to", $5}'
	done
}

function subdomain_check {
	dig "${2}"."$1" +noall +answer | \
    awk -v subdomain="$2" '{print "The subdomain", subdomain, "is a", $4, "record and points to", $5}'
}

if [ $# -lt 1 ]
then
	echo "*** Provide domain name ***"
elif [ $# -eq 1 ]
then
	domain_check "$1";
else
	subdomain_check "$1" "$2";
fi