#!/usr/bin/env bash
# Bash script that will display information about subdomains.
subdomains=("www" "lb-01" "web-01" "web-02")

# Function that displays info about a specific subdomain or all subdomains
display() {
    # Checks if a subdomain name was provided before parsing
    if [ $# -lt 2 ]; then
        for sub_name in "${subdomains[@]}"; do
            dig "$sub_name"."$1" +noall +answer | awk -v subdomain="$sub_name" '{print "The subdomain ", subdomain, " is a ", $4, " record and points to ", $5}'
        done
    else
        dig "$2"."$1" +noall +answer | awk -v subdomain="$2" '{print "The subdomain ", subdomain, " is a ", $4, " record and points to ", $5}'
    fi

}

# Checks if a subdomain name was provided before parsing
if [ $# -lt 2 ]; then
    display "$1"
else
    display "$1" "$2"
fi
