#!/usr/bin/env bash
# Bash script that will display information about subdomains.
subdomains=("www" "lb-01" "web-01" "web-02")

# Function that displays info about a specific subdomain or all subdomains
display() {
    # Checks if a subdomain name was provided before parsing
    if [ $# -lt 2 ]; then
        for sub_name in "${subdomains[@]}";
        do
            dig "${sub_name}"."$1" +noall +answer | \
            awk '{printf "The subdomain %s is a %s record and points to %s\n", subdomain, $4, $5}' subdomain="$sub_name"
        done
    else
        dig "${2}"."$1" +noall +answer | \
        awk '{printf "The subdomain %s is a %s record and points to %s\n", subdomain, $4, $5}' subdomain="$2"
    fi

}

# Checks if a subdomain name was provided before parsing
if [ $# -lt 1 ]
then
	echo "*** Provide domain name ***"
elif [ $# -eq 1 ]
then
	display "$1";
else
	display "$1" "$2";
fi
