#!/usr/bin/env bash
#  Bash script containing commands to automatically configure a redirect
# on a new Ubuntu machine

sudo su <<EOF

apt-get -y update
apt-get install -y nginx

# Configure Nginx to listen on port 80
ufw allow 'Nginx HTTP'

# start Nginx
service nginx start

# Create a file with "Hello World!" message
echo "Hello World!" > /var/www/html/index.html

# add permanent redirection
my_new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com permanent;"
sudo sed -i "s/server_name _;/$my_new_string/" /etc/nginx/sites-enabled/default


service nginx restart

EOF
