#!/usr/bin/env bash
#Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page

sudo apt-get -y update
sudo apt-get install -y nginx

# Configure Nginx to listen on port 80
sudo ufw allow 'Nginx HTTP'

# start Nginx
sudo service nginx start

# With root priviledges, create a file with "Hello World!" message
sudo su <<DELIMETER
echo "Hello World!" > /var/www/html/index.html;
DELIMETER

# add permanent redirection
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/tami-cp0 permanent;"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

# code to create error page and add a redirect for error 404
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
my_new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$my_new_string/" /etc/nginx/sites-enabled/default


# Get the hostname
hostname=$(hostname)
# Set custom response header
echo "add_header X-Served-By $hostname;" | sudo tee /etc/nginx/conf.d/custom_header.conf

# restart the server
sudo service nginx restart