#!/usr/bin/env bash
# web stack debugging
# remove and reinstall it
sudo rm /etc/nginx/sites-enabled/default;
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default;
# start service
sudo service nginx restart
