#!/usr/bin/env bash
# web stack debugging
# remove and reinstall it
apt-get remove nginx --purge
apt-get install -y nginx
rm /etc/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/sites-enabled/default;
# start service
service nginx restart
