#!/usr/bin/env bash
# script that configures the container to listen on port 8080 and run on nginx user.
sudo sed -i '1 s/#user www-data;/user nginx;/' /etc/nginx/nginx.conf
sudo sed -i 's/server {/server {\n\tlisten 8080;/' /etc/nginx/sites-available/default
sudo service nginx restart
