#!/usr/bin/env bash
# script that configures the container to listen on port 8080 and run on nginx user. IN 7 lines or less
sudo sed -i '1 s/#user www-data/user nginx/' /etc/nginx/nginx.conf
sudo sed -i 's/server {/server {\n\tlisten 8080;/' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
